project_id = "tlanmmbgyyxuqvezudir"

[functions.send-payment-notification]
verify_jwt = false

[functions.send-referral-notification]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-whatsapp-uazapi]
verify_jwt = false

[functions.whatsapp-instances]
verify_jwt = false

[functions.campaigns]
verify_jwt = false

[functions.generate-warming-message]
verify_jwt = false

[functions.warming-worker]
verify_jwt = false
