project_id = "eocrnjbdrrvuhhdwskvn"

[functions.send-expiration-reminder]
verify_jwt = false

[functions.daily-expiration-check]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false
