project_id = "eocrnjbdrrvuhhdwskvn"

[functions.send-expiration-reminder]
verify_jwt = false

[functions.daily-expiration-check]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.send-payment-notification]
verify_jwt = false

[functions.auto-send-reminders]
verify_jwt = false

[functions.send-referral-notification]
verify_jwt = false

[functions.send-whatsapp-evolution]
verify_jwt = false
