project_id = "tlanmmbgyyxuqvezudir"

[functions.send-expiration-reminder]
verify_jwt = false

[functions.daily-expiration-check]
verify_jwt = false

[functions.process-scheduled-messages]
verify_jwt = false

[functions.send-payment-notification]
verify_jwt = false

[functions.auto-send-reminders]
verify_jwt = false

[functions.send-referral-notification]
verify_jwt = false

[functions.send-whatsapp-evolution]
verify_jwt = false

[functions.send-whatsapp-media]
verify_jwt = false

[functions.check-whatsapp-numbers]
verify_jwt = false

[functions.create-whatsapp-instance]
verify_jwt = false

[functions.get-whatsapp-instance]
verify_jwt = false

[functions.get-whatsapp-qrcode]
verify_jwt = false
